### ISSUE TITLE
Investigate about form

### ISSUE THREAD

**Issue by juanjoseortega-aircury** [curacultura/curacultura-website#59]
Investigate about creating a form or maybe a google form.

https://docs.google.com/document/d/1NjaGujf9XZnsCqHsKOFZYxwZWZh7lhhDi_wjI2qVuiA/edit?usp=sharing

**Comment by cristobaldiaz-aircury** [comment]
Consider to be added add into the document:
1. Using Google forms but from a custom interface. This would require extra work but in exchange we would have it integrated in our own page, instead of a redirection, and we would have full control of the style.
2. It was proposed to add a contact form, therefore we should consider how to use the chosen solution for it.

**Comment by cristobaldiaz-aircury** [comment]
Pending update with the latest requirements discussed with the client.
